name: "Deploy to Cloudflare"
on: [push, workflow_dispatch]

jobs:
  upload-to-cloudflare-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Staging Directory for Sync
        run: |
          echo "Creating staging directory (dist)"
          mkdir dist
          echo "Copying deployment artifacts to staging directory (dist)"
          cp -R css dist/
          cp -R fonts dist/
          cp -R images dist/
          cp index.html dist/
      - name: Upload to R2
        run: |
          aws s3 sync ./dist s3://${CF_R2_BUCKET_NAME}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
